### ISSUE TITLE
Heading Change? (not in body of doc)

### ISSUE THREAD

**Issue by eben-ei** [Effective-Immediately/effective-immediately#14]
Proposal: replace 

"Everything an employer, employee, or recently laid-off person might want to know about layoffs during a pandemic"

With:
"Layoffs are hard. Help each other-- everything an employer, colleague, or recently laid-off job seeker might want for support after layoffs."

Or maybe the crisper:
"Layoffs are hard. Help each other-- everything an employer, colleague, or job seeker can use for support after layoffs."

**Comment by kristalane** [comment]
Complete!
