### ISSUE TITLE
Convert to Static Site

### ISSUE THREAD

**Issue by aviflombaum** [Effective-Immediately/effective-immediately#26]
I think we should make this repository into a GitHub Pages website so that people don't have to interact with the GitHub interface to read the content.

My vote would be to use [Middleman](https://github.com/middleman/middleman) I have a lot of experience with it. I mostly like Middleman over [Jekyll](https://jekyllrb.com/) because of the choices in templating however given that this is really a content site, I think Jekyll would work well with Markdown/Liquid.

Other options (sourced from [StaticGen](https://www.staticgen.com/)):

https://gohugo.io/
https://slatedocs.github.io/slate/#introduction
https://docsify.js.org/#/
https://docusaurus.io/

They all seem very Documentation-centric and overly complex.

With all of these we can use auto-deploy on push to master and we can point to a custom domain (I got [EffectiveImmediately.org](https://www.effectiveimmediately.org) and [Effective-Immediately.org](https://www.effective-immediately.org))

**Comment by kristalane** [comment]
Static site was definitely on the medium-term road map-- thank you for pushing us forward and providing proposed solutions! I agree, a static site is more optimal for usability and accessibility. 

My main concern is around ease of backend maintenance-- I'm just dusting off my command line and markdown rust and while community support is great, I do at least kinda want to know what I'm doing (even if I'm slow) so I don't have to rely on community contributions 100%. 

Secondarily-- and this may be less important-- most of my (limited / from 3 years ago) code familiarity is in JS and Python, so I'm happy to give it a shot/learn something new, but want to make sure a Ruby-based thing would be manageable.

Are there any Middleman tutorials you recommend so I could get more up to speed?

**Comment by aviflombaum** [comment]
I can setup the site and everything so you don't need to worry about build/backend/command line stuff - you just push to master or update master and the static site will redeploy. I'll set it up on my fork and show you how it works, I don't even think we need to worry about contributors even having Ruby - you just update the repo and GitHub will do the actions to build the site and update.

**Comment by aviflombaum** [comment]
So I set it up on my fork: https://aviflombaum.github.io/effective-immediately/ (though for the org site it would just be effective-immediately.org). I can edit the theme and layout so that the TOC is a sticky navigation and obviously update all the contact information etc. *BUT the important thing is* if you just edit the MD files on GitHub (using the GitHub Editor Even), like index.md and push the branch (or just update the branch) GitHub will rebuild Jekyll automatically so you don't need to have Ruby/Jekyll installed to contribute.

**Comment by kristalane** [comment]
Hey, I appreciate the work you've put into this so far! We'll need some to review and discuss (and have a weekend) but didn't want to leave you hanging without a response. We'll try to get back to you early next week.

**Comment by kristalane** [comment]
sorry for delay! haven't forgotten! some job interviews and other calls got moved around and the three of us still haven't had a chance to discuss. if you'd like to set up a zoom call, feel free to email us your availability to effectiveimmediately3@gmail.com

**Comment by aviflombaum** [comment]
Closing, let me know if you want to reopen at any point.
