### ISSUE TITLE
Include mention of Cal-COBRA

### ISSUE THREAD

**Issue by mejarc** [Effective-Immediately/effective-immediately#37]
If you've exhausted your federal COBRA eligibility, you might be eligible for [more months of COBRA coverage under California law](https://www.dmhc.ca.gov/HealthCareinCalifornia/TypesofPlans/KeepYourHealthCoverage(COBRA).aspx).

**Comment by kristalane** [comment]
thank you! Will add shortly (sorry for the delay, didn't see the notification)

**Comment by mysouto** [comment]
Added!
